server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "98829f4739af204a37fe51823b144ad85aa32d779bd5eaa269ad12895cfd7d4a"
